[package]
name = "romst"
version = "0.1.0"
authors = ["Nico Hormazabal <mail@nico.red>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
quick-xml = "0.20.0"